### ISSUE TITLE
Add composer registry

### ISSUE THREAD

**Issue by kontur** [fzerorubigd/silex-lazy-thumbnail-generator#1]
Currently this package is not discoverable through composer. I suggest you add it on https://packagist.org/ so others can install it more easily.

**Comment by fzerorubigd** [comment]
Its already there :) 

https://packagist.org/packages/fzerorubigd/silex-lazy-thumbnail-generator

**Comment by kontur** [comment]
Weird; I couldn't find it via `composer search ...`, but an explicit `composer require fzerorubigd/silex-lazy-thumbnail-generator` does indeed find it. My bad.
